"""add scanner key to events

Revision ID: c18d5df95868
Revises: ccc9367b73c4
Create Date: 2026-02-19 02:42:13.572393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18d5df95868'
down_revision: Union[str, Sequence[str], None] = 'ccc9367b73c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scanner_key', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_events_scanner_key'), 'events', ['scanner_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_scanner_key'), table_name='events')
    op.drop_column('events', 'scanner_key')
    # ### end Alembic commands ###
